### ISSUE TITLE
Requested Feature - Quick Reply

### ISSUE THREAD

**Issue by Singleton06** [gyandeeps/crucible-canned-responses#1]
I like the idea of the plugin, but I think it would be nice to an additional feature such that it could automatically respond with the response.  It would be nice if I could designate these quick replies such that they are only a single click (and I can configure which ones show up).

It would be something similar to the following:
![image](https://cloud.githubusercontent.com/assets/2235110/18182317/19ade3a2-7055-11e6-971f-779166d1fe0e.png)

Where clicking the +1 or addressed would just respond to the comment without having to click anything else.

**Comment by gyandeeps** [comment]
Are you talking about this feature https://github.com/gyandeeps/crucible-canned-responses#with-auto-comment-turned-on ?

**Comment by gyandeeps** [comment]
Ah now i see, you asking for an option on the existing comment so that if you click that thing then it auto-responds to that comment with the thing.

The thing could be configured by the user example +1

Did i get it right @Singleton06 ?

**Comment by Singleton06** [comment]
Yes, that would be correct.  In the above example, if I clicked the +1 (to the right of the 14:52 text) it would auto reply with +1 to the comment.  Or if I clicked the "addressed" it would auto-comment to the comment the text is attached to with "addressed".

**Comment by gyandeeps** [comment]
Sounds good to me. 
I will work on it when I get time and I also need to clean up the code base because when i developed this i was also learning how to build chrome plugins.

**Comment by Singleton06** [comment]
Awesome!  Thanks.

**Comment by gyandeeps** [comment]
@Singleton06 I created the functionality and uploaded the package to chrome store.
Docs: https://github.com/gyandeeps/crucible-canned-responses#quick-reply

Update your extension in 1 hr from now (1pm cst) then you should be able to get it.

**Comment by Singleton06** [comment]
Awesome! Unfortunately I can't get to crucible right now, but as soon as I can I will check this feature out.  Thanks for doing this.

**Comment by Singleton06** [comment]
I was able to get into crucible, it works great.  Thanks for adding the feature!
