### ISSUE TITLE
Canned responses not available after adjusting revisions

### ISSUE THREAD

**Issue by Singleton06** [gyandeeps/crucible-canned-responses#3]
I noticed an issue that seems to be related to adjusting the revisions that are being displayed.  On the first load of the page, the options for replying with pre-canned responses is available and works as expected.

However, if I adjust the revisions slider toward the top of the screen, after the page finishes loading the revisions diff, the pre-canned responses go away and is no longer an option for me to select.
![image](https://cloud.githubusercontent.com/assets/2235110/18329773/d28c66f4-751a-11e6-9fe9-c18493169332.png)

Here's what I see when clicking reply:
![image](https://cloud.githubusercontent.com/assets/2235110/18329809/09db8aa4-751b-11e6-839d-025106ef69fb.png)

**Comment by gyandeeps** [comment]
Are you talking about quick reply option or the pre-canned response with a dropdown?

**Comment by Singleton06** [comment]
Sorry I didn't respond sooner...  It is actually both.
